export const FIND_RENTS_REQUEST = 'FIND_RENTS_REQUEST';
export const FIND_RENTS_SUCCESS = 'FIND_RENTS_SUCCESS';
export const FIND_RENTS_FAILURE = 'FIND_RENTS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const OAUTH_REQUEST = 'OAUTH_REQUEST';
export const OAUTH_FAILURE = 'OAUTH_FAILURE';
export const OAUTH_SUCCESS = 'OAUTH_SUCCESS';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const FIND_REGISTER_REQUEST = 'FIND_REGISTER_REQUEST';
export const FIND_REGISTER_FAILURE = 'FIND_REGISTER_FAILURE';
export const FIND_REGISTER_SUCCESS = 'FIND_REGISTER_SUCCESS';

export const FIND_ACCOUNT_REQUEST = 'FIND_ACCOUNT_REQUEST';
export const FIND_ACCOUNT_FAILURE = 'FIND_ACCOUNT_FAILURE';
export const FIND_ACCOUNT_SUCCESS = 'FIND_ACCOUNT_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const FIND_RENT_REQUEST = 'FIND_RENT_REQUEST';
export const FIND_RENT_SUCCESS = 'FIND_RENT_SUCCESS';
export const FIND_RENT_FAILURE = 'FIND_RENT_FAILURE';

export const FIND_RENTBORROWED_REQUEST = 'FIND_RENTBORROWED_REQUEST';
export const FIND_RENTBORROWED_SUCCESS = 'FIND_RENTBORROWED_SUCCESS';
export const FIND_RENTBORROWED_FAILURE = 'FIND_RENTBORROWED_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FIND_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FIND_ITEMS_FAILURE';

export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST';
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS';
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE';

export const EDIT_ITEM_REQUEST = 'EDIT_ITEM_REQUEST';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_FAILURE = 'EDIT_ITEM_FAILURE';

export const FIND_RENTSBORROWED_REQUEST = 'FIND_RENTSBORROWED_REQUEST';
export const FIND_RENTSBORROWED_SUCCESS = 'FIND_RENTSBORROWED_SUCCESS';
export const FIND_RENTSBORROWED_FAILURE = 'FIND_RENTSBORROWED_FAILURE';

export const FIND_RENTSDONE_REQUEST = 'FIND_RENTSDONE_REQUEST';
export const FIND_RENTSDONE_SUCCESS = 'FIND_RENTSDONE_SUCCESS';
export const FIND_RENTSDONE_FAILURE = 'FIND_RENTSDONE_FAILURE';

export const SAVE_RENT_REQUEST = 'SAVE_RENT_REQUEST';
export const SAVE_RENT_FAILURE = 'SAVE_RENT_FAILURE';
export const SAVE_RENT_SUCCESS = 'SAVE_RENT_SUCCESS';

export const FIND_TRANSACTIONS_REQUEST = 'FIND_TRANSACTIONS_REQUEST';
export const FIND_TRANSACTIONS_SUCCESS = 'FIND_TRANSACTIONS_SUCCESS';
export const FIND_TRANSACTIONS_FAILURE = 'FIND_TRANSACTIONS_FAILURE';

export const FIND_TRANSACTION_REQUEST = 'FIND_TRANSACTION_REQUEST';
export const FIND_TRANSACTION_SUCCESS = 'FIND_TRANSACTION_SUCCESS';
export const FIND_TRANSACTION_FAILURE = 'FIND_TRANSACTION_FAILURE';

export const SAVE_TRANSACTION_REQUEST = 'SAVE_TRANSACTION_REQUEST';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS';
export const SAVE_TRANSACTION_FAILURE = 'SAVE_TRANSACTION_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';



